name: itc
channels:
  - ankurankan
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _pytorch_select=0.2
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.1.5
  - ca-certificates=2020.6.20
  - cudatoolkit=10.0.130
  - cudnn=7.6.5
  - cycler=0.10.0
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.9
  - fontconfig=2.13.1
  - freetype=2.10.2
  - glib=2.65.0
  - icu=58.2
  - importlib-metadata=1.6.1
  - importlib_metadata=1.6.1
  - intel-openmp=2020.1
  - ipykernel=5.3.0
  - ipython=7.15.0
  - ipython_genutils=0.2.0
  - jedi=0.17.0
  - jinja2=2.11.2
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter_client=6.1.3
  - jupyter_core=4.6.3
  - krb5=1.16.4
  - libffi=3.3
  - libpng=1.6.37
  - libpq=11.2
  - libsodium=1.0.17
  - libxcb=1.13
  - libxml2=2.9.10
  - markupsafe=1.1.1
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.0
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - ninja=1.9.0
  - notebook=6.0.3
  - numpy-base=1.18.1
  - openssl=1.1.1g
  - packaging=20.4
  - pandoc=2.9.2.1
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - pomegranate=0.11.1
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.5
  - psycopg2=2.8.4
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pygments=2.6.1
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - python=3.7.7
  - python_abi=3.7
  - pytorch=1.3.1
  - pyzmq=19.0.1
  - qt=5.9.7
  - send2trash=1.5.0
  - setuptools=47.1.1
  - sip=4.19.8
  - sqlite=3.31.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - tornado=6.0.4
  - traitlets=4.3.3
  - wcwidth=0.2.4
  - webencodings=0.5.1
  - wheel=0.34.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.1.7
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - pip:
    - arff==0.9
    - asn1crypto==0.24.0
    - atomicwrites==1.3.0
    - attrs==19.1.0
    - bloom-filter==1.3
    - certifi==2019.3.9
    - cffi==1.12.3
    - chardet==3.0.4
    - cloudpickle==1.2.1
    - colorama==0.4.1
    - cryptography==2.9.2
    - dask==1.2.0
    - decorator==4.4.0
    - ete3==3.1.1
    - idna==2.6
    - joblib==0.13.2
    - keyring==10.6.0
    - keyrings-alt==3.0
    - kiwisolver==1.1.0
    - lark-parser==0.7.1
    - locket==0.2.0
    - matplotlib==3.0.3
    - mock==3.0.4
    - more-itertools==7.0.0
    - mpmath==1.1.0
    - networkx==2.3
    - numexpr==2.6.9
    - numpy==1.16.3
    - pandas==0.23.4
    - partd==1.0.0
    - patsy==0.5.1
    - pluggy==0.9.0
    - py==1.8.0
    - py4j==0.10.8.1
    - pybind11==2.3.0
    - pycparser==2.19
    - pycrypto==2.6.1
    - pydot==1.4.1
    - pyparsing==2.4.0
    - pyqt5==5.12.1
    - pyqt5-sip==4.19.15
    - pytest==4.4.1
    - python-dateutil==2.7.5
    - pytz==2018.7
    - pyverdict==0.1.3.2
    - pyxdg==0.25
    - pyyaml==3.12
    - requests==2.18.4
    - scikit-learn==0.20.3
    - scipy==1.2.1
    - secretstorage==2.3.1
    - six==1.12.0
    - sklearn==0.0
    - spflow==0.0.34
    - sqlalchemy==1.3.11
    - sqlparse==0.3.0
    - statsmodels==0.9.0
    - sympy==1.4
    - tables==3.5.1
    - toolz==0.9.0
    - tqdm==4.31.1
    - urllib3==1.22
    - var-dump==1.2
    - wincertstore==0.2
# prefix: /home/ziniu.wzn/anaconda3/envs/deepdb

